import type { Metadata } from "next";
import { Raleway, IBM_Plex_Mono, Kanit, Syne, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const fontSerif = Syne({
   variable: "--font-serif",
   subsets: ["latin"],
})

const fontThai = Kanit({
   variable: "--font-thai",
   subsets: ["thai"],
   weight: ["100", "200", "300", "400", "500"]
})

const fontMono = IBM_Plex_Mono({
   variable: "--font-mono",
   subsets: ["latin"],
   weight: ["100", "200", "300", "400", "500"]
});

export const metadata: Metadata = {
   title: "Natcha Memento",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={cn("h-full", "antialiased", fontThai.variable, fontSerif.variable, fontMono.variable, "font-sans", inter.variable)}
      >
         <body className="min-h-full flex flex-col">
            {children}
         </body>
      </html>
   );
}
